/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nanapiyasa.view;

import com.ijse.sms.controller.BackUpController;
import java.awt.Color;
import java.awt.Component;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author Randula
 */
public class AdminSettings extends javax.swing.JFrame {

    /**
     * Creates new form AdminSettings
     */
    public AdminSettings() {
        initComponents();
        ManageStudent f1 = new ManageStudent();
        panel.removeAll();
        f1.setSize(panel.getSize());
        Component add = panel.add(f1);
        panel.repaint();
        panel.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        manageCourseLbl = new javax.swing.JLabel();
        manageStudentLbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        manageClassLbl = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        manageExaminationLbl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        manageLecturerLbl = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        manageMarksLbl = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        manageCertificateLbl = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        manageTimetable = new javax.swing.JLabel();
        backupBtn = new javax.swing.JButton();
        restore = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Admin Settings");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/background2.png"))); // NOI18N
        panel.add(jLabel2);
        jLabel2.setBounds(0, 82, 835, 528);

        jPanel1.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 900, 630));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Manage Students");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 110, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Manage Courses");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 100, 50));

        manageCourseLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        manageCourseLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/labelSize.png"))); // NOI18N
        manageCourseLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        manageCourseLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageCourseLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageCourseLblMouseClicked(evt);
            }
        });
        jPanel1.add(manageCourseLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 210, 50));

        manageStudentLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        manageStudentLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/labelSize.png"))); // NOI18N
        manageStudentLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        manageStudentLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageStudentLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageStudentLblMouseClicked(evt);
            }
        });
        jPanel1.add(manageStudentLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 210, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Manage Classes");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 150, 50));

        manageClassLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        manageClassLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/labelSize.png"))); // NOI18N
        manageClassLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        manageClassLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageClassLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageClassLblMouseClicked(evt);
            }
        });
        jPanel1.add(manageClassLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 210, 50));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Manage Examinations");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 140, 50));

        manageExaminationLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        manageExaminationLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/labelSize.png"))); // NOI18N
        manageExaminationLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        manageExaminationLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageExaminationLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageExaminationLblMouseClicked(evt);
            }
        });
        jPanel1.add(manageExaminationLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 210, 50));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Manage Lecturers");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 140, 50));

        manageLecturerLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        manageLecturerLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/labelSize.png"))); // NOI18N
        manageLecturerLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        manageLecturerLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageLecturerLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageLecturerLblMouseClicked(evt);
            }
        });
        jPanel1.add(manageLecturerLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 210, 50));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Manage Marks");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 140, 50));

        manageMarksLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        manageMarksLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/labelSize.png"))); // NOI18N
        manageMarksLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        manageMarksLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageMarksLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageMarksLblMouseClicked(evt);
            }
        });
        jPanel1.add(manageMarksLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 210, 50));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Manage Certificates");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 140, 50));

        manageCertificateLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        manageCertificateLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/labelSize.png"))); // NOI18N
        manageCertificateLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        manageCertificateLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageCertificateLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageCertificateLblMouseClicked(evt);
            }
        });
        jPanel1.add(manageCertificateLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 210, 50));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Manage Timetable");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 140, 50));

        manageTimetable.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        manageTimetable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/labelSize.png"))); // NOI18N
        manageTimetable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        manageTimetable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageTimetable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageTimetableMouseClicked(evt);
            }
        });
        jPanel1.add(manageTimetable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 210, 50));

        backupBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/backUp.png"))); // NOI18N
        backupBtn.setToolTipText("Back Up Database");
        backupBtn.setContentAreaFilled(false);
        backupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backupBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backupBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 60, 60));

        restore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/restore.png"))); // NOI18N
        restore.setToolTipText("Restore Datebase");
        restore.setBorderPainted(false);
        restore.setContentAreaFilled(false);
        restore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restoreActionPerformed(evt);
            }
        });
        jPanel1.add(restore, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 570, 60, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/background.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1160, 596));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void manageStudentLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageStudentLblMouseClicked
        ManageStudent f1 = new ManageStudent();
        panel.removeAll();
        f1.setSize(panel.getSize());
        Component add = panel.add(f1);
        panel.repaint();
        panel.revalidate();

        manageStudentLbl.setBorder(new LineBorder(Color.orange, 3));
        manageCourseLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageClassLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageExaminationLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageLecturerLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageMarksLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageCertificateLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageTimetable.setBorder(new LineBorder(new Color(204, 0, 0), 1));

    }//GEN-LAST:event_manageStudentLblMouseClicked

    private void manageCourseLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageCourseLblMouseClicked
        ManageCourse f1 = new ManageCourse();
        panel.removeAll();
        f1.setSize(panel.getSize());
        Component add = panel.add(f1);
        panel.repaint();
        panel.revalidate();
        
        manageCourseLbl.setBorder(new LineBorder(Color.orange, 3));
        manageStudentLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageClassLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageExaminationLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageLecturerLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageMarksLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageCertificateLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageTimetable.setBorder(new LineBorder(new Color(204, 0, 0), 1));
    }//GEN-LAST:event_manageCourseLblMouseClicked

    private void manageClassLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageClassLblMouseClicked
        ManageClass f1 = new ManageClass();
        panel.removeAll();
        f1.setSize(panel.getSize());
        Component add = panel.add(f1);
        panel.repaint();
        panel.revalidate();
        
          manageClassLbl.setBorder(new LineBorder(Color.orange, 3));
        manageStudentLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageCourseLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageExaminationLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageLecturerLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageMarksLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageCertificateLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageTimetable.setBorder(new LineBorder(new Color(204, 0, 0), 1));
                                               
    }//GEN-LAST:event_manageClassLblMouseClicked

    private void manageExaminationLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageExaminationLblMouseClicked
        ManageExams f1 = new ManageExams();
        panel.removeAll();
        f1.setSize(panel.getSize());
        Component add = panel.add(f1);
        panel.repaint();
        panel.revalidate();
        
            manageExaminationLbl.setBorder(new LineBorder(Color.orange, 3));
        manageStudentLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageCourseLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageClassLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageLecturerLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageMarksLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageCertificateLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageTimetable.setBorder(new LineBorder(new Color(204, 0, 0), 1));
    }//GEN-LAST:event_manageExaminationLblMouseClicked

    private void manageLecturerLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageLecturerLblMouseClicked
        ManageLecturer f1 = new ManageLecturer();
        panel.removeAll();
        f1.setSize(panel.getSize());
        Component add = panel.add(f1);
        panel.repaint();
        panel.revalidate();
        
              manageLecturerLbl.setBorder(new LineBorder(Color.orange, 3));
        manageStudentLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageCourseLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageClassLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageExaminationLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageMarksLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageCertificateLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageTimetable.setBorder(new LineBorder(new Color(204, 0, 0), 1));
    }//GEN-LAST:event_manageLecturerLblMouseClicked

    private void manageMarksLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageMarksLblMouseClicked
        ManageMark f1 = new ManageMark();
        panel.removeAll();
        f1.setSize(panel.getSize());
        Component add = panel.add(f1);
        panel.repaint();
        panel.revalidate();
                     manageMarksLbl.setBorder(new LineBorder(Color.orange, 3));
        manageStudentLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageCourseLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageClassLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageExaminationLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageLecturerLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageCertificateLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageTimetable.setBorder(new LineBorder(new Color(204, 0, 0), 1));
    }//GEN-LAST:event_manageMarksLblMouseClicked

    private void manageCertificateLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageCertificateLblMouseClicked
        ManageCertificate f1 = new ManageCertificate();
        panel.removeAll();
        f1.setSize(panel.getSize());
        Component add = panel.add(f1);
        panel.repaint();
        panel.revalidate();
        
                     manageCertificateLbl.setBorder(new LineBorder(Color.orange, 3));
        manageStudentLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageCourseLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageClassLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageExaminationLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageMarksLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageLecturerLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageTimetable.setBorder(new LineBorder(new Color(204, 0, 0), 1));
    }//GEN-LAST:event_manageCertificateLblMouseClicked

    private void manageTimetableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageTimetableMouseClicked
        ManageTimetable f1 = new ManageTimetable();
        panel.removeAll();
        f1.setSize(panel.getSize());
        Component add = panel.add(f1);
        panel.repaint();
        panel.revalidate();
        
                     manageTimetable.setBorder(new LineBorder(Color.orange, 3));
        manageStudentLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageCourseLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageClassLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageExaminationLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageMarksLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageCertificateLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        manageLecturerLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
    }//GEN-LAST:event_manageTimetableMouseClicked

    private void backupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backupBtnActionPerformed
        try {
            JFileChooser fc = new JFileChooser();
            fc.showOpenDialog(this);
            File file = fc.getSelectedFile();
            String path = file.getAbsolutePath();
            System.out.println(path);
            
            
            int res = BackUpController.writeBackup(path);
            if (res == 0) {
                JOptionPane.showMessageDialog(this, "Backed Up");
            } else {
                JOptionPane.showMessageDialog(this, "Back Up Failed");
            }
        } catch (IOException ex) {
            Logger.getLogger(AdminSettings.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(AdminSettings.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_backupBtnActionPerformed

    private void restoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restoreActionPerformed
        try {
            JFileChooser fc = new JFileChooser();
            fc.showOpenDialog(this);
            File file = fc.getSelectedFile();
            String path = file.getAbsolutePath();
            
            int res = BackUpController.restoreBackup(path);
            if (res == 0) {
                JOptionPane.showMessageDialog(this, "Successfully Restored");
            }else{
               JOptionPane.showMessageDialog(this, "Resore Failed");
            }
        } catch (IOException ex) {
            Logger.getLogger(AdminSettings.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(AdminSettings.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_restoreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminSettings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backupBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel manageCertificateLbl;
    private javax.swing.JLabel manageClassLbl;
    private javax.swing.JLabel manageCourseLbl;
    private javax.swing.JLabel manageExaminationLbl;
    private javax.swing.JLabel manageLecturerLbl;
    private javax.swing.JLabel manageMarksLbl;
    private javax.swing.JLabel manageStudentLbl;
    private javax.swing.JLabel manageTimetable;
    private javax.swing.JPanel panel;
    private javax.swing.JButton restore;
    // End of variables declaration//GEN-END:variables
}
