/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nanapiyasa.view;

import java.awt.Component;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import com.ijse.sms.controller.CourseController;
import com.ijse.sms.controller.PaymentController;
import com.ijse.sms.controller.RegistrationController;
import com.ijse.sms.controller.StudentController;
import com.ijse.sms.model.Course;
import com.ijse.sms.model.Payment;
import com.ijse.sms.model.Registration;
import com.ijse.sms.model.Student;

/**
 *
 * @author Randula
 */
public class AdvancedSearchCourse extends javax.swing.JPanel {

    /**
     * Creates new form AdvancedSearchCourse
     */
    public AdvancedSearchCourse() {
        initComponents();
        arrangeCombo();
    }
    public void arrangeCombo(){
        try {
            ArrayList<Student>studentList=StudentController.viewAllStudent();
            for(Student student:studentList){
                  stIdCombo.addItem(student.getStID());
            }
           
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageStudent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ManageStudent.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }
    public String settleCourse(String cId){
        try {
            ArrayList<Course>courseList=CourseController.viewAllcourse();
            for(Course course:courseList){
                if(cId.equals(course.getCourseID())){
                    return course.getCourseName();
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdvancedSearchCourse.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdvancedSearchCourse.class.getName()).log(Level.SEVERE, null, ex);
        }
        return "";
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        reloadBtn = new javax.swing.JButton();
        durationLbl2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        modifyBtn = new javax.swing.JButton();
        stIdCombo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setPreferredSize(new java.awt.Dimension(900, 630));
        panel.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Advanced Search Courses");
        panel.add(jLabel2);
        jLabel2.setBounds(0, 0, 900, 40);

        reloadBtn.setBackground(new java.awt.Color(255, 233, 248));
        reloadBtn.setText("Reload");
        reloadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadBtnActionPerformed(evt);
            }
        });
        panel.add(reloadBtn);
        reloadBtn.setBounds(310, 500, 110, 30);

        durationLbl2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        durationLbl2.setText("Reason");
        panel.add(durationLbl2);
        durationLbl2.setBounds(-420, 410, 60, 30);

        table.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Registration ID", "course", "Registration fee", "Registered Date", "Class "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setFillsViewportHeight(true);
        table.setGridColor(new java.awt.Color(204, 0, 0));
        table.setSelectionBackground(new java.awt.Color(255, 204, 153));
        table.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setPreferredWidth(5);
            table.getColumnModel().getColumn(2).setMinWidth(200);
            table.getColumnModel().getColumn(2).setPreferredWidth(200);
            table.getColumnModel().getColumn(2).setMaxWidth(200);
            table.getColumnModel().getColumn(3).setMinWidth(100);
            table.getColumnModel().getColumn(3).setPreferredWidth(100);
            table.getColumnModel().getColumn(3).setMaxWidth(100);
        }

        panel.add(jScrollPane1);
        jScrollPane1.setBounds(50, 120, 790, 350);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Student ID");
        panel.add(jLabel3);
        jLabel3.setBounds(50, 80, 80, 30);

        modifyBtn.setBackground(new java.awt.Color(255, 233, 248));
        modifyBtn.setText("Modify");
        modifyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyBtnActionPerformed(evt);
            }
        });
        panel.add(modifyBtn);
        modifyBtn.setBounds(490, 500, 110, 30);

        stIdCombo.setEditable(true);
        stIdCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "none" }));
        stIdCombo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        stIdCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stIdComboActionPerformed(evt);
            }
        });
        panel.add(stIdCombo);
        stIdCombo.setBounds(130, 80, 190, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/background2.png"))); // NOI18N
        panel.add(jLabel1);
        jLabel1.setBounds(0, 90, 835, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void modifyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyBtnActionPerformed
       new ModifyCourses(null, true).setVisible(true);
    }//GEN-LAST:event_modifyBtnActionPerformed

    private void stIdComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stIdComboActionPerformed
          try {
            ArrayList<Registration>registrationList=RegistrationController.viewAllRegistrationDetail();
             DefaultTableModel dtm = (DefaultTableModel) table.getModel();
             dtm.setRowCount(0);
             String stId=(String)stIdCombo.getSelectedItem();
            for(Registration registration: registrationList){
                String cId=registration.getCourseID();
                if(registration.getStID().equals(stId)){
                Object[] rows={registration.getStID(),registration.getRegID(),settleCourse(cId),registration.getRegFee(),registration.getRegDate(),registration.getClassDetail()};
		dtm.addRow(rows);
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ViewPayment.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ViewPayment.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       
        
    }//GEN-LAST:event_stIdComboActionPerformed

    private void reloadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadBtnActionPerformed
         try {
            ArrayList<Registration>registrationList=RegistrationController.viewAllRegistrationDetail();
             DefaultTableModel dtm = (DefaultTableModel) table.getModel();
             dtm.setRowCount(0);
             String stId=(String)stIdCombo.getSelectedItem();
            for(Registration registration: registrationList){
                String cId=registration.getCourseID();
                if(registration.getStID().equals(stId)){
                Object[] rows={registration.getStID(),registration.getRegID(),settleCourse(cId),registration.getRegFee(),registration.getRegDate(),registration.getClassDetail()};
		dtm.addRow(rows);
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ViewPayment.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ViewPayment.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_reloadBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel durationLbl2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton modifyBtn;
    private javax.swing.JPanel panel;
    private javax.swing.JButton reloadBtn;
    private javax.swing.JComboBox stIdCombo;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
