/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nanapiyasa.view;

import java.awt.Component;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import com.ijse.sms.controller.StudentController;
import com.ijse.sms.util.Validation;
import com.ijse.sms.model.Student;

/**
 *
 * @author Randula
 */
public class ManageStudent extends javax.swing.JPanel {

    /**
     * Creates new form ManageStudent
     */
    public ManageStudent() {
        initComponents();
        arrangeCombo();
    }

    public void arrangeCombo() {
        try {
            ArrayList<Student> studentList = StudentController.viewAllStudent();
            for (Student student : studentList) {
                stIdCombo.addItem(student.getStID());
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ManageStudent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ManageStudent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guardTelTxt = new javax.swing.JTextField();
        dobLbl = new javax.swing.JLabel();
        idLbl1 = new javax.swing.JLabel();
        telLbl = new javax.swing.JLabel();
        addressLbl = new javax.swing.JLabel();
        relationshipLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        occupationLbl = new javax.swing.JLabel();
        genderLbl = new javax.swing.JLabel();
        guardTelLbl = new javax.swing.JLabel();
        guardLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        occupationTxt = new javax.swing.JTextField();
        relationshipTxt = new javax.swing.JTextField();
        genderTxt = new javax.swing.JTextField();
        guardTxt = new javax.swing.JTextField();
        dobTxt = new javax.swing.JTextField();
        telTxt = new javax.swing.JTextField();
        addressTxt = new javax.swing.JTextField();
        nameTxt = new javax.swing.JTextField();
        clearBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        stIdCombo = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(900, 630));
        setLayout(null);

        guardTelTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        guardTelTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                guardTelTxtKeyTyped(evt);
            }
        });
        add(guardTelTxt);
        guardTelTxt.setBounds(270, 460, 470, 35);

        dobLbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        dobLbl.setText("DOB  ");
        add(dobLbl);
        dobLbl.setBounds(210, 230, 40, 20);

        idLbl1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        idLbl1.setText("Student ID");
        add(idLbl1);
        idLbl1.setBounds(200, 60, 70, 20);

        telLbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        telLbl.setText("Telephone ");
        add(telLbl);
        telLbl.setBounds(210, 190, 70, 20);

        addressLbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        addressLbl.setText("Address");
        add(addressLbl);
        addressLbl.setBounds(210, 140, 60, 35);

        relationshipLbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        relationshipLbl.setText("Relationship");
        add(relationshipLbl);
        relationshipLbl.setBounds(200, 420, 80, 35);

        nameLbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        nameLbl.setText("Name  ");
        add(nameLbl);
        nameLbl.setBounds(210, 100, 50, 20);

        occupationLbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        occupationLbl.setText("Occupation");
        add(occupationLbl);
        occupationLbl.setBounds(200, 380, 70, 35);

        genderLbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        genderLbl.setText("Gender");
        add(genderLbl);
        genderLbl.setBounds(210, 270, 50, 20);

        guardTelLbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        guardTelLbl.setText(" Telephone ");
        add(guardTelLbl);
        guardTelLbl.setBounds(200, 470, 70, 20);

        guardLbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        guardLbl.setText("Guardian");
        add(guardLbl);
        guardLbl.setBounds(200, 350, 60, 20);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Search Student Details");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 900, 40);

        occupationTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        add(occupationTxt);
        occupationTxt.setBounds(270, 380, 470, 35);

        relationshipTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        add(relationshipTxt);
        relationshipTxt.setBounds(270, 420, 470, 35);

        genderTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        add(genderTxt);
        genderTxt.setBounds(270, 260, 470, 35);

        guardTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        add(guardTxt);
        guardTxt.setBounds(270, 340, 470, 35);

        dobTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        add(dobTxt);
        dobTxt.setBounds(270, 220, 470, 35);

        telTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        add(telTxt);
        telTxt.setBounds(270, 180, 470, 35);

        addressTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        add(addressTxt);
        addressTxt.setBounds(270, 140, 470, 35);

        nameTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        add(nameTxt);
        nameTxt.setBounds(270, 100, 470, 35);

        clearBtn.setBackground(new java.awt.Color(255, 233, 248));
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        add(clearBtn);
        clearBtn.setBounds(760, 460, 110, 30);

        editBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/Edit.png"))); // NOI18N
        editBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editBtnMouseClicked(evt);
            }
        });
        add(editBtn);
        editBtn.setBounds(430, 510, 80, 70);

        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/Delete.png"))); // NOI18N
        deleteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBtnMouseClicked(evt);
            }
        });
        add(deleteBtn);
        deleteBtn.setBounds(550, 520, 70, 60);

        jLabel3.setText("Remove");
        add(jLabel3);
        jLabel3.setBounds(560, 580, 50, 20);

        jLabel6.setText("Save Changes");
        add(jLabel6);
        jLabel6.setBounds(430, 580, 70, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/background2.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 90, 835, 520);

        stIdCombo.setEditable(true);
        stIdCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "none" }));
        stIdCombo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        stIdCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stIdComboActionPerformed(evt);
            }
        });
        add(stIdCombo);
        stIdCombo.setBounds(270, 50, 470, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void stIdComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stIdComboActionPerformed

        String id = (String) stIdCombo.getSelectedItem();
        if (id != "none") {
            try {
                Student student = StudentController.searchStudent(id);
                if (student != null) {
                    nameTxt.setText(student.getStName());
                    addressTxt.setText(student.getStAddress());
                    telTxt.setText(student.getStTelephone());
                    dobTxt.setText(student.getdOB());
                    genderTxt.setText(student.getGender());
                    guardTxt.setText(student.getGuardName());
                    occupationTxt.setText(student.getGuardOccupation());
                    relationshipTxt.setText(student.getGuardRelationship());
                    guardTelTxt.setText(student.getGuardTelephone());
                } else {
                    JOptionPane.showMessageDialog(this, "Student Does Not Exist");
                    stIdCombo.setSelectedItem("none");
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ManageStudent.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(ManageStudent.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            nameTxt.setText(null);
            addressTxt.setText(null);
            telTxt.setText(null);
            dobTxt.setText(null);
            genderTxt.setText(null);
            guardTxt.setText(null);
            occupationTxt.setText(null);
            relationshipTxt.setText(null);
            guardTelTxt.setText(null);
        }
    }//GEN-LAST:event_stIdComboActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        nameTxt.setText(null);
        addressTxt.setText(null);
        telTxt.setText(null);
        dobTxt.setText(null);
        genderTxt.setText(null);
        guardTxt.setText(null);
        occupationTxt.setText(null);
        relationshipTxt.setText(null);
        guardTelTxt.setText(null);
    }//GEN-LAST:event_clearBtnActionPerformed

    private void editBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBtnMouseClicked
        int res = JOptionPane.showOptionDialog(this, "Dou you want to save changes?", "Options", 0, 0, null, null, null);
        if (res == 0) {
            String id = (String) stIdCombo.getSelectedItem();
            String name = nameTxt.getText();
            String address = addressTxt.getText();
            String tel = telTxt.getText();
            String dob = dobTxt.getText();
            String gender = genderTxt.getText();
            String guard = guardTxt.getText();
            String occupation = occupationTxt.getText();
            String relationship = relationshipTxt.getText();
            String guardTel = guardTelTxt.getText();

            Student student = new Student(id, name, address, tel, dob, gender, guard, occupation, relationship, guardTel);

            try {
                boolean isUpdated = StudentController.updateStudent(student);
                if (isUpdated) {
                    JOptionPane.showMessageDialog(this, "Successfully Saved");
                } else {
                    JOptionPane.showMessageDialog(this, "Saving Failed");
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ManageStudent.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(ManageStudent.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_editBtnMouseClicked

    private void deleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseClicked
        int res = JOptionPane.showOptionDialog(this, "Dou you want to Delete this Student?", "Options", 0, 0, null, null, null);
        if (res == 0) {
            String id = (String) stIdCombo.getSelectedItem();
            try {

                boolean isDeleted = StudentController.deleteStudent(id);
                if (isDeleted) {
                    JOptionPane.showMessageDialog(this, "Student Removed");
                    stIdCombo.setSelectedItem("none");
                    arrangeCombo();
                } else {
                    JOptionPane.showMessageDialog(this, "Try Again");
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_deleteBtnMouseClicked

    private void guardTelTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_guardTelTxtKeyTyped
        Validation.phoneNumber(guardTelTxt, evt);
    }//GEN-LAST:event_guardTelTxtKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLbl;
    private javax.swing.JTextField addressTxt;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel deleteBtn;
    private javax.swing.JLabel dobLbl;
    private javax.swing.JTextField dobTxt;
    private javax.swing.JLabel editBtn;
    private javax.swing.JLabel genderLbl;
    private javax.swing.JTextField genderTxt;
    private javax.swing.JLabel guardLbl;
    private javax.swing.JLabel guardTelLbl;
    private javax.swing.JTextField guardTelTxt;
    private javax.swing.JTextField guardTxt;
    private javax.swing.JLabel idLbl1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JLabel occupationLbl;
    private javax.swing.JTextField occupationTxt;
    private javax.swing.JLabel relationshipLbl;
    private javax.swing.JTextField relationshipTxt;
    private javax.swing.JComboBox stIdCombo;
    private javax.swing.JLabel telLbl;
    private javax.swing.JTextField telTxt;
    // End of variables declaration//GEN-END:variables
}
