/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nanapiyasa.view;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Randula
 */
public class NanapiyasaHome extends javax.swing.JFrame {

    /**
     * Creates new form NanapiyasaHome
     */
    private Payments pm;
    private SearchStudent ss;
    private RegisterStudent reg;
    private StudentAttendance at;
    private AdminSettings as;
    private Courses cs;
    private Timetables tt;
    private Lecturers lec;
    private Examinations ex;
    private Reports rp;
    boolean isVisible = false;
    boolean isUserVisible = false;
    private String userType;
    public NanapiyasaHome() {
        initComponents();
        sidePanel.setVisible(isVisible);
        userP.setVisible(isUserVisible);
        ArrangeMenus();
        setDate();
        autoTime();
    }

    public NanapiyasaHome(String type) {
        initComponents();
        sidePanel.setVisible(isVisible);
        userP.setVisible(isUserVisible);
        setDate();
        autoTime();
        ArrangeMenus();
        userP.setVisible(false);
        if (type.equals("Admin")) {
            adminBtn.setEnabled(true);
            addUserBtn.setEnabled(true);
            this.userType="Admin";
        } else {
            this.userType="User";
            //adminBtn.setEnabled(false);
            addUserBtn.setVisible(false);
        }

    }

    public void ArrangeMenus() {
        m1.setVisible(false);
        m4.setVisible(false);
        m2.setVisible(false);
        m5.setVisible(false);
        m6.setVisible(false);
       m7.setVisible(false);
    }

    public void setDate() {
        String date = new SimpleDateFormat("YYYY-MM-dd").format(new Date());
        dateLbl.setText(date);
    }

    private void autoTime() {
        new Thread(new Runnable() {
            public void run() {
                while (true) {
                    Date time = new Date();
                    String curTime = new SimpleDateFormat("hh:mm:ss aa").format(time);
                    timeShow.setText(curTime);
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {

                    }
                }
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registrationBtn = new javax.swing.JLabel();
        paymentBtn = new javax.swing.JLabel();
        adminBtn = new javax.swing.JLabel();
        searchBtn = new javax.swing.JLabel();
        attendanceBtn = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        timeShow = new javax.swing.JLabel();
        jCalendar1 = new org.freixas.jcalendar.JCalendar();
        addUserBtn = new javax.swing.JLabel();
        userP = new javax.swing.JPanel();
        user = new javax.swing.JLabel();
        releaseCertificateLbl1 = new javax.swing.JLabel();
        dateLbl = new javax.swing.JLabel();
        sidePanel = new javax.swing.JPanel();
        coursesBtn = new javax.swing.JLabel();
        timetableBtn = new javax.swing.JLabel();
        reportBtn = new javax.swing.JLabel();
        lecturerBtn = new javax.swing.JLabel();
        examBtn = new javax.swing.JLabel();
        certificateBtn = new javax.swing.JLabel();
        manuBtn = new javax.swing.JButton();
        m2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        viewTimetableLbl = new javax.swing.JLabel();
        m1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        viewAllCourseslbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        advancedSearchCombo = new javax.swing.JLabel();
        m4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ViewAllLecturerLbl1 = new javax.swing.JLabel();
        m5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        viewExaminationTxt = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        manageMarksLbl = new javax.swing.JLabel();
        m6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        paymentAlertTxt = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        regStatusLbl = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        chartBtn = new javax.swing.JLabel();
        m7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        viewAllResult = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        releaseCertificateLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1217, 618));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registrationBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/registrations.png"))); // NOI18N
        registrationBtn.setToolTipText("Registrations");
        registrationBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrationBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrationBtnMouseClicked(evt);
            }
        });
        getContentPane().add(registrationBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 70, 70));

        paymentBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/payments.png"))); // NOI18N
        paymentBtn.setToolTipText("Payments");
        paymentBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paymentBtn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                paymentBtnFocusGained(evt);
            }
        });
        paymentBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paymentBtnMouseClicked(evt);
            }
        });
        getContentPane().add(paymentBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 70, 70));

        adminBtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        adminBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/settings.png"))); // NOI18N
        adminBtn.setToolTipText(" Settings");
        adminBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminBtnMouseClicked(evt);
            }
        });
        getContentPane().add(adminBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 370, 70, 70));

        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/search.png"))); // NOI18N
        searchBtn.setToolTipText("Search Students");
        searchBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBtnMouseClicked(evt);
            }
        });
        getContentPane().add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 70, 70));

        attendanceBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/attendance.png"))); // NOI18N
        attendanceBtn.setToolTipText("Attendance");
        attendanceBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        attendanceBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attendanceBtnMouseClicked(evt);
            }
        });
        getContentPane().add(attendanceBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, 60, 70));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        timeShow.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        timeShow.setForeground(new java.awt.Color(204, 51, 0));
        timeShow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(timeShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 240, 50));
        jPanel1.add(jCalendar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 350, 230));

        addUserBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/userManage.png"))); // NOI18N
        addUserBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addUserBtnMouseClicked(evt);
            }
        });
        jPanel1.add(addUserBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, 50));

        userP.setOpaque(false);
        userP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userPMouseClicked(evt);
            }
        });
        userP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        user.setText("New User");
        user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userMouseEntered(evt);
            }
        });
        userP.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 30));

        releaseCertificateLbl1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        releaseCertificateLbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/labelSize.png"))); // NOI18N
        releaseCertificateLbl1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        releaseCertificateLbl1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        releaseCertificateLbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                releaseCertificateLbl1MouseClicked(evt);
            }
        });
        userP.add(releaseCertificateLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 30));

        jPanel1.add(userP, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 100, 50));

        dateLbl.setBackground(new java.awt.Color(255, 153, 0));
        dateLbl.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        dateLbl.setForeground(new java.awt.Color(204, 51, 0));
        dateLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(dateLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 260, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 390, 570));

        sidePanel.setOpaque(false);

        coursesBtn.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        coursesBtn.setForeground(new java.awt.Color(255, 255, 255));
        coursesBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        coursesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/courses.png"))); // NOI18N
        coursesBtn.setText("   Courses");
        coursesBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        coursesBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                coursesBtnMouseMoved(evt);
            }
        });
        coursesBtn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                coursesBtnFocusGained(evt);
            }
        });
        coursesBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                coursesBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                coursesBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                coursesBtnMouseExited(evt);
            }
        });

        timetableBtn.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        timetableBtn.setForeground(new java.awt.Color(255, 255, 255));
        timetableBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        timetableBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/timetable_1.png"))); // NOI18N
        timetableBtn.setText("   Timetable");
        timetableBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        timetableBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timetableBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                timetableBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                timetableBtnMouseExited(evt);
            }
        });

        reportBtn.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        reportBtn.setForeground(new java.awt.Color(255, 255, 255));
        reportBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        reportBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/reports.png"))); // NOI18N
        reportBtn.setText("  Reports");
        reportBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reportBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportBtnMouseExited(evt);
            }
        });

        lecturerBtn.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        lecturerBtn.setForeground(new java.awt.Color(255, 255, 255));
        lecturerBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lecturerBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/lecturer.png"))); // NOI18N
        lecturerBtn.setText(" Lecturers");
        lecturerBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lecturerBtn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lecturerBtnMouseMoved(evt);
            }
        });
        lecturerBtn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lecturerBtnFocusLost(evt);
            }
        });
        lecturerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lecturerBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lecturerBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lecturerBtnMouseExited(evt);
            }
        });

        examBtn.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        examBtn.setForeground(new java.awt.Color(255, 255, 255));
        examBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        examBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/examination.png"))); // NOI18N
        examBtn.setText("    Examinations");
        examBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        examBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                examBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                examBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                examBtnMouseExited(evt);
            }
        });

        certificateBtn.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        certificateBtn.setForeground(new java.awt.Color(255, 255, 255));
        certificateBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        certificateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/certificates.png"))); // NOI18N
        certificateBtn.setText("    Certificates");
        certificateBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        certificateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                certificateBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                certificateBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                certificateBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addComponent(certificateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
            .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(sidePanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(coursesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addComponent(timetableBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addComponent(reportBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addComponent(examBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addComponent(lecturerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(0, 30, Short.MAX_VALUE)))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanelLayout.createSequentialGroup()
                .addContainerGap(259, Short.MAX_VALUE)
                .addComponent(certificateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(sidePanelLayout.createSequentialGroup()
                    .addGap(0, 10, Short.MAX_VALUE)
                    .addComponent(coursesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(timetableBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(reportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(lecturerBtn)
                    .addGap(10, 10, 10)
                    .addComponent(examBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 60, Short.MAX_VALUE)))
        );

        getContentPane().add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 210, 310));

        manuBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/menu.png"))); // NOI18N
        manuBtn.setContentAreaFilled(false);
        manuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manuBtnActionPerformed(evt);
            }
        });
        getContentPane().add(manuBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 50));

        m2.setOpaque(false);
        m2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                m2MouseClicked(evt);
            }
        });
        m2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("View Timetable");
        m2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 100, 50));

        viewTimetableLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        viewTimetableLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/labelSize.png"))); // NOI18N
        viewTimetableLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        viewTimetableLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewTimetableLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewTimetableLblMouseClicked(evt);
            }
        });
        m2.add(viewTimetableLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 50));

        getContentPane().add(m2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, 60));

        m1.setOpaque(false);
        m1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                m1FocusLost(evt);
            }
        });
        m1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                m1MouseExited(evt);
            }
        });
        m1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("View All Courses");
        m1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 100, 50));

        viewAllCourseslbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        viewAllCourseslbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/labelSize.png"))); // NOI18N
        viewAllCourseslbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        viewAllCourseslbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewAllCourseslbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewAllCourseslblMouseClicked(evt);
            }
        });
        m1.add(viewAllCourseslbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 50));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Advanced Search Course");
        m1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, 50));

        advancedSearchCombo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        advancedSearchCombo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/labelSize.png"))); // NOI18N
        advancedSearchCombo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        advancedSearchCombo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        advancedSearchCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                advancedSearchComboMouseClicked(evt);
            }
        });
        m1.add(advancedSearchCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 150, 50));

        getContentPane().add(m1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 440, 50));

        m4.setOpaque(false);
        m4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                m4FocusLost(evt);
            }
        });
        m4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                m4MouseExited(evt);
            }
        });
        m4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("View All Lectures");
        m4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 110, 50));

        ViewAllLecturerLbl1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ViewAllLecturerLbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/labelSize.png"))); // NOI18N
        ViewAllLecturerLbl1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        ViewAllLecturerLbl1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewAllLecturerLbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewAllLecturerLbl1MouseClicked(evt);
            }
        });
        m4.add(ViewAllLecturerLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 50));

        getContentPane().add(m4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 210, 60));

        m5.setOpaque(false);
        m5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("View Examinations");
        m5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 110, 50));

        viewExaminationTxt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        viewExaminationTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/labelSize.png"))); // NOI18N
        viewExaminationTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        viewExaminationTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewExaminationTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewExaminationTxtMouseClicked(evt);
            }
        });
        m5.add(viewExaminationTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 150, 50));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setText("Create Mark Sheet");
        m5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 110, 50));

        manageMarksLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        manageMarksLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/labelSize.png"))); // NOI18N
        manageMarksLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        manageMarksLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageMarksLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageMarksLblMouseClicked(evt);
            }
        });
        m5.add(manageMarksLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 50));

        getContentPane().add(m5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 610, 50));

        m6.setOpaque(false);
        m6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Payment Alerts");
        m6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 130, 50));

        paymentAlertTxt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        paymentAlertTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/labelSize.png"))); // NOI18N
        paymentAlertTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        paymentAlertTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paymentAlertTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paymentAlertTxtMouseClicked(evt);
            }
        });
        m6.add(paymentAlertTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 50));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("Registration Status");
        m6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 110, 50));

        regStatusLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        regStatusLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/labelSize.png"))); // NOI18N
        regStatusLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        regStatusLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regStatusLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regStatusLblMouseClicked(evt);
            }
        });
        m6.add(regStatusLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 140, 50));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("Charts");
        m6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 110, 50));

        chartBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        chartBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/labelSize.png"))); // NOI18N
        chartBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        chartBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chartBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chartBtnMouseClicked(evt);
            }
        });
        m6.add(chartBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 150, 50));

        getContentPane().add(m6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 590, -1));

        m7.setOpaque(false);
        m7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                m7MouseExited(evt);
            }
        });
        m7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("View Results");
        m7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 110, 50));

        viewAllResult.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        viewAllResult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/labelSize.png"))); // NOI18N
        viewAllResult.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        viewAllResult.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewAllResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewAllResultMouseClicked(evt);
            }
        });
        m7.add(viewAllResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 50));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Release Certificates");
        m7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, 50));

        releaseCertificateLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        releaseCertificateLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/labelSize.png"))); // NOI18N
        releaseCertificateLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        releaseCertificateLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        releaseCertificateLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                releaseCertificateLblMouseClicked(evt);
            }
        });
        m7.add(releaseCertificateLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 150, 50));

        getContentPane().add(m7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 610, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/banner3.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 510));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nanapiyasa Rural Education Develpment & Vocational Training Institute");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 40, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 830, 70));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registrationBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrationBtnMouseClicked
        if (reg == null) {
            reg = new RegisterStudent();
        }
        reg.setVisible(true);
    }//GEN-LAST:event_registrationBtnMouseClicked

    private void paymentBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paymentBtnMouseClicked
        if (pm == null) {
            pm = new Payments();
        }
        pm.setVisible(true);
    }//GEN-LAST:event_paymentBtnMouseClicked

    private void searchBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnMouseClicked
        if (ss == null) {
            ss = new SearchStudent();
        }
        ss.setVisible(true);
    }//GEN-LAST:event_searchBtnMouseClicked

    private void attendanceBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendanceBtnMouseClicked
        if (at == null) {
            at = new StudentAttendance();
        }
        at.setVisible(true);
    }//GEN-LAST:event_attendanceBtnMouseClicked

    private void adminBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminBtnMouseClicked
        if (as == null) {
            as = new AdminSettings();
        }
        as.setVisible(true);
    }//GEN-LAST:event_adminBtnMouseClicked

    private void coursesBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coursesBtnMouseClicked
        m1.setVisible(true);
        m4.setVisible(false);
        m2.setVisible(false);
        m5.setVisible(false);
        m6.setVisible(false);
    }//GEN-LAST:event_coursesBtnMouseClicked

    private void coursesBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coursesBtnMouseEntered
        coursesBtn.setForeground(Color.orange);

    }//GEN-LAST:event_coursesBtnMouseEntered

    private void timetableBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timetableBtnMouseClicked
        m2.setVisible(true);
    }//GEN-LAST:event_timetableBtnMouseClicked

    private void reportBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportBtnMouseClicked
        m6.setVisible(true);
    }//GEN-LAST:event_reportBtnMouseClicked

    private void lecturerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lecturerBtnMouseClicked
        m4.setVisible(true);
    }//GEN-LAST:event_lecturerBtnMouseClicked

    private void examBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_examBtnMouseClicked
        m5.setVisible(true);
    }//GEN-LAST:event_examBtnMouseClicked

    private void manuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manuBtnActionPerformed
        ArrangeMenus();
        if (isVisible) {
            isVisible = false;
            sidePanel.setVisible(isVisible);
        } else {
            isVisible = true;
            sidePanel.setVisible(isVisible);
        }
    }//GEN-LAST:event_manuBtnActionPerformed

    private void coursesBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coursesBtnMouseMoved
        //
    }//GEN-LAST:event_coursesBtnMouseMoved

    private void coursesBtnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_coursesBtnFocusGained

    }//GEN-LAST:event_coursesBtnFocusGained

    private void coursesBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coursesBtnMouseExited
        coursesBtn.setForeground(Color.white);

    }//GEN-LAST:event_coursesBtnMouseExited

    private void timetableBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timetableBtnMouseEntered
        timetableBtn.setForeground(Color.orange);
        m4.setVisible(false);
        m1.setVisible(false);
        m5.setVisible(false);
        m6.setVisible(false);
        m7.setVisible(false);
    }//GEN-LAST:event_timetableBtnMouseEntered

    private void timetableBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timetableBtnMouseExited
        timetableBtn.setForeground(Color.white);
    }//GEN-LAST:event_timetableBtnMouseExited

    private void reportBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportBtnMouseEntered
        reportBtn.setForeground(Color.orange);
        m4.setVisible(false);
        m1.setVisible(false);
        m2.setVisible(false);
        m5.setVisible(false);
        m7.setVisible(false);
    }//GEN-LAST:event_reportBtnMouseEntered

    private void reportBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportBtnMouseExited
        reportBtn.setForeground(Color.white);
    }//GEN-LAST:event_reportBtnMouseExited

    private void lecturerBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lecturerBtnMouseEntered
        lecturerBtn.setForeground(Color.orange);
        m2.setVisible(false);
        m1.setVisible(false);
        m5.setVisible(false);
        m6.setVisible(false);
         m7.setVisible(false);
    }//GEN-LAST:event_lecturerBtnMouseEntered

    private void lecturerBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lecturerBtnMouseExited
        lecturerBtn.setForeground(Color.white);


    }//GEN-LAST:event_lecturerBtnMouseExited

    private void examBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_examBtnMouseEntered
        examBtn.setForeground(Color.orange);
        m4.setVisible(false);
        m1.setVisible(false);
        m2.setVisible(false);
        m6.setVisible(false);
         m7.setVisible(false);
    }//GEN-LAST:event_examBtnMouseEntered

    private void examBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_examBtnMouseExited
        examBtn.setForeground(Color.white);
    }//GEN-LAST:event_examBtnMouseExited

    private void lecturerBtnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lecturerBtnMouseMoved

    }//GEN-LAST:event_lecturerBtnMouseMoved

    private void m1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m1MouseExited
        m4.setVisible(false);
        m2.setVisible(false);
        m5.setVisible(false);
        m6.setVisible(false);
         m1.setVisible(false);
    }//GEN-LAST:event_m1MouseExited

    private void m1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m1FocusLost

    }//GEN-LAST:event_m1FocusLost

    private void lecturerBtnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lecturerBtnFocusLost

    }//GEN-LAST:event_lecturerBtnFocusLost

    private void ViewAllLecturerLbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewAllLecturerLbl1MouseClicked
        new Lecturers("ViewAll").setVisible(true);
    }//GEN-LAST:event_ViewAllLecturerLbl1MouseClicked

    private void m4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m4FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_m4FocusLost

    private void m4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_m4MouseExited

    private void viewAllCourseslblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewAllCourseslblMouseClicked
        new Courses("ViewAll").setVisible(true);
    }//GEN-LAST:event_viewAllCourseslblMouseClicked

    private void advancedSearchComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_advancedSearchComboMouseClicked
        new Courses("AdvancedSearch").setVisible(true);
    }//GEN-LAST:event_advancedSearchComboMouseClicked

    private void viewTimetableLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewTimetableLblMouseClicked
        new Timetables("ViewTimeTable").setVisible(true);
    }//GEN-LAST:event_viewTimetableLblMouseClicked

    private void m2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m2MouseClicked
        m4.setVisible(false);
        m1.setVisible(false);
        m5.setVisible(false);
    }//GEN-LAST:event_m2MouseClicked

    private void viewExaminationTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewExaminationTxtMouseClicked
        new Examinations("ViewExam").setVisible(true);
    }//GEN-LAST:event_viewExaminationTxtMouseClicked

    private void viewAllResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewAllResultMouseClicked
        new Examinations("ViewResult").setVisible(true);

    }//GEN-LAST:event_viewAllResultMouseClicked

    private void releaseCertificateLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_releaseCertificateLblMouseClicked
        new Examinations("ReleaseCertificate").setVisible(true);
    }//GEN-LAST:event_releaseCertificateLblMouseClicked

    private void releaseCertificateLbl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_releaseCertificateLbl1MouseClicked
      
    }//GEN-LAST:event_releaseCertificateLbl1MouseClicked

    private void addUserBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addUserBtnMouseClicked
        if (isUserVisible) {
            userP.setVisible(false);
            isUserVisible = false;
        } else {
            userP.setVisible(true);
            isUserVisible = true;
        }
    }//GEN-LAST:event_addUserBtnMouseClicked

    private void userPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userPMouseClicked

    }//GEN-LAST:event_userPMouseClicked

    private void userMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_userMouseEntered

    private void userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMouseClicked
        new SignUp(null, true).setVisible(true);
    }//GEN-LAST:event_userMouseClicked

    private void paymentBtnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paymentBtnFocusGained

    }//GEN-LAST:event_paymentBtnFocusGained

    private void paymentAlertTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paymentAlertTxtMouseClicked
        new PaymentAlerts().setVisible(true);

    }//GEN-LAST:event_paymentAlertTxtMouseClicked

    private void regStatusLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regStatusLblMouseClicked
       new ClassAlerts().setVisible(true);
    }//GEN-LAST:event_regStatusLblMouseClicked

    private void chartBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chartBtnMouseClicked
        new Reports().setVisible(true);
    }//GEN-LAST:event_chartBtnMouseClicked

    private void certificateBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_certificateBtnMouseClicked
       m7.setVisible(true);
    }//GEN-LAST:event_certificateBtnMouseClicked

    private void certificateBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_certificateBtnMouseEntered
          certificateBtn.setForeground(Color.orange);
           
        m2.setVisible(false);
        m1.setVisible(false);
        m5.setVisible(false);
        m6.setVisible(false);
    }//GEN-LAST:event_certificateBtnMouseEntered

    private void certificateBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_certificateBtnMouseExited
       certificateBtn.setForeground(Color.white);

    }//GEN-LAST:event_certificateBtnMouseExited

    private void manageMarksLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageMarksLblMouseClicked
         new Examinations("ManageMarks").setVisible(true);
    }//GEN-LAST:event_manageMarksLblMouseClicked

    private void m7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m7MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_m7MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NanapiyasaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NanapiyasaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NanapiyasaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NanapiyasaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NanapiyasaHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ViewAllLecturerLbl1;
    private javax.swing.JLabel addUserBtn;
    private javax.swing.JLabel adminBtn;
    private javax.swing.JLabel advancedSearchCombo;
    private javax.swing.JLabel attendanceBtn;
    private javax.swing.JLabel certificateBtn;
    private javax.swing.JLabel chartBtn;
    private javax.swing.JLabel coursesBtn;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JLabel examBtn;
    private org.freixas.jcalendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lecturerBtn;
    private javax.swing.JPanel m1;
    private javax.swing.JPanel m2;
    private javax.swing.JPanel m4;
    private javax.swing.JPanel m5;
    private javax.swing.JPanel m6;
    private javax.swing.JPanel m7;
    private javax.swing.JLabel manageMarksLbl;
    private javax.swing.JButton manuBtn;
    private javax.swing.JLabel paymentAlertTxt;
    private javax.swing.JLabel paymentBtn;
    private javax.swing.JLabel regStatusLbl;
    private javax.swing.JLabel registrationBtn;
    private javax.swing.JLabel releaseCertificateLbl;
    private javax.swing.JLabel releaseCertificateLbl1;
    private javax.swing.JLabel reportBtn;
    private javax.swing.JLabel searchBtn;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JLabel timeShow;
    private javax.swing.JLabel timetableBtn;
    private javax.swing.JLabel user;
    private javax.swing.JPanel userP;
    private javax.swing.JLabel viewAllCourseslbl;
    private javax.swing.JLabel viewAllResult;
    private javax.swing.JLabel viewExaminationTxt;
    private javax.swing.JLabel viewTimetableLbl;
    // End of variables declaration//GEN-END:variables
}
