/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nanapiyasa.view;

import java.awt.Color;
import java.awt.Component;
import javax.swing.border.LineBorder;

/**
 *
 * @author Randula
 */
public class Payments extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
    public Payments() {
        initComponents();
        DoPayment f1 = new DoPayment();
        panel.removeAll();
        f1.setSize(panel.getSize());
        Component add = panel.add(f1);
        panel.repaint();
        panel.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        refundPayment = new javax.swing.JLabel();
        settlePaymentLbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        viewPaymentLbl = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ViewRefund = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        advancedSearch = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Payments");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(900, 630));
        jPanel3.setLayout(null);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/background2.png"))); // NOI18N
        jPanel3.add(jLabel16);
        jLabel16.setBounds(0, 90, 835, 520);

        panel.add(jPanel3);
        jPanel3.setBounds(0, 0, 900, 630);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/background2.png"))); // NOI18N
        panel.add(jLabel2);
        jLabel2.setBounds(0, 82, 835, 528);

        jPanel1.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 900, 630));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Settle Payments");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 110, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Refund Payments");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 120, 50));

        refundPayment.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        refundPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/labelSize.png"))); // NOI18N
        refundPayment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        refundPayment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refundPayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refundPaymentMouseClicked(evt);
            }
        });
        jPanel1.add(refundPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 210, 50));

        settlePaymentLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        settlePaymentLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/labelSize.png"))); // NOI18N
        settlePaymentLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        settlePaymentLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        settlePaymentLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settlePaymentLblMouseClicked(evt);
            }
        });
        jPanel1.add(settlePaymentLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 210, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("View  Payments");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 150, 50));

        viewPaymentLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        viewPaymentLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/labelSize.png"))); // NOI18N
        viewPaymentLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        viewPaymentLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewPaymentLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewPaymentLblMouseClicked(evt);
            }
        });
        jPanel1.add(viewPaymentLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 210, 50));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("View Refunds");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 140, 50));

        ViewRefund.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ViewRefund.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/labelSize.png"))); // NOI18N
        ViewRefund.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        ViewRefund.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewRefund.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewRefundMouseClicked(evt);
            }
        });
        jPanel1.add(ViewRefund, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 210, 50));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Advanced Search");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 140, 50));

        advancedSearch.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        advancedSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/labelSize.png"))); // NOI18N
        advancedSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        advancedSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        advancedSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                advancedSearchMouseClicked(evt);
            }
        });
        jPanel1.add(advancedSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 210, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/background.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1160, 596));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void refundPaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refundPaymentMouseClicked
        DoRefund f1 = new DoRefund();
        panel.removeAll();
        f1.setSize(panel.getSize());
        Component add = panel.add(f1);
        panel.repaint();
        panel.revalidate();

        refundPayment.setBorder(new LineBorder(Color.orange, 3));
        viewPaymentLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        ViewRefund.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        advancedSearch.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        settlePaymentLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
    }//GEN-LAST:event_refundPaymentMouseClicked

    private void settlePaymentLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settlePaymentLblMouseClicked
        DoPayment f1 = new DoPayment();
        panel.removeAll();
        f1.setSize(panel.getSize());
        Component add = panel.add(f1);
        panel.repaint();
        panel.revalidate();

        settlePaymentLbl.setBorder(new LineBorder(Color.orange, 3));
        viewPaymentLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        ViewRefund.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        advancedSearch.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        refundPayment.setBorder(new LineBorder(new Color(204, 0, 0), 1));
    }//GEN-LAST:event_settlePaymentLblMouseClicked

    private void viewPaymentLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewPaymentLblMouseClicked
        ViewPayment f1 = new ViewPayment();
        panel.removeAll();
        f1.setSize(panel.getSize());
        Component add = panel.add(f1);
        panel.repaint();
        panel.revalidate();

        viewPaymentLbl.setBorder(new LineBorder(Color.orange, 3));
        ViewRefund.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        advancedSearch.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        settlePaymentLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        refundPayment.setBorder(new LineBorder(new Color(204, 0, 0), 1));
    }//GEN-LAST:event_viewPaymentLblMouseClicked

    private void ViewRefundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewRefundMouseClicked
        ViewRefund f1 = new ViewRefund();
        panel.removeAll();
        f1.setSize(panel.getSize());
        Component add = panel.add(f1);
        panel.repaint();
        panel.revalidate();
        ViewRefund.setBorder(new LineBorder(Color.orange, 3));
        advancedSearch.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        settlePaymentLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        viewPaymentLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        settlePaymentLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        refundPayment.setBorder(new LineBorder(new Color(204, 0, 0), 1));
    }//GEN-LAST:event_ViewRefundMouseClicked

    private void advancedSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_advancedSearchMouseClicked
        AdvancedSearchPayment f1 = new AdvancedSearchPayment();
        panel.removeAll();
        f1.setSize(panel.getSize());
        Component add = panel.add(f1);
        panel.repaint();
        panel.revalidate();

        advancedSearch.setBorder(new LineBorder(Color.orange, 3));
        settlePaymentLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        viewPaymentLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        refundPayment.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        ViewRefund.setBorder(new LineBorder(new Color(204, 0, 0), 1));
    }//GEN-LAST:event_advancedSearchMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ViewRefund;
    private javax.swing.JLabel advancedSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel refundPayment;
    private javax.swing.JLabel settlePaymentLbl;
    private javax.swing.JLabel viewPaymentLbl;
    // End of variables declaration//GEN-END:variables
}
