/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nanapiyasa.view;

import java.awt.Color;
import java.awt.Component;
import javax.swing.border.LineBorder;

/**
 *
 * @author Randula
 */
public class SearchStudent extends javax.swing.JFrame {

    /**
     * Creates new form SearchStudent
     */
    public SearchStudent() {
        initComponents();
        ManageStudent f1=new ManageStudent();
        panel.removeAll();
        f1.setSize(panel.getSize());
        Component add = panel.add(f1);
        panel.repaint();
        panel.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        searchStudentLbl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        statusLbl = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        advancedSearch = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search Students");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/background2.png"))); // NOI18N
        panel.add(jLabel2);
        jLabel2.setBounds(0, 82, 835, 528);

        jPanel1.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 900, 630));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Search  Students");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 120, 50));

        searchStudentLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        searchStudentLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/labelSize.png"))); // NOI18N
        searchStudentLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        searchStudentLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchStudentLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchStudentLblMouseClicked(evt);
            }
        });
        jPanel1.add(searchStudentLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 210, 50));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Student Summery");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 140, 50));

        statusLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/labelSize.png"))); // NOI18N
        statusLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        statusLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        statusLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statusLblMouseClicked(evt);
            }
        });
        jPanel1.add(statusLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 210, 50));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Search By Name");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 140, 50));

        advancedSearch.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        advancedSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/labelSize.png"))); // NOI18N
        advancedSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        advancedSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        advancedSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                advancedSearchMouseClicked(evt);
            }
        });
        jPanel1.add(advancedSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 210, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/background.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1160, 596));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchStudentLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchStudentLblMouseClicked
        ManageStudent f1=new ManageStudent();
        panel.removeAll();
        f1.setSize(panel.getSize());
        Component add = panel.add(f1);
        panel.repaint();
        panel.revalidate();
        
        searchStudentLbl.setBorder(new LineBorder(Color.orange, 3));        
        statusLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
        advancedSearch.setBorder(new LineBorder(new Color(204, 0, 0), 1));
    }//GEN-LAST:event_searchStudentLblMouseClicked

    private void statusLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statusLblMouseClicked
        StudentSummery f1=new StudentSummery();
        panel.removeAll();
        f1.setSize(panel.getSize());
        Component add = panel.add(f1);
        panel.repaint();
        panel.revalidate();
        
        statusLbl.setBorder(new LineBorder(Color.orange, 3));       
        searchStudentLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
       advancedSearch.setBorder(new LineBorder(new Color(204, 0, 0), 1));
    }//GEN-LAST:event_statusLblMouseClicked

    private void advancedSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_advancedSearchMouseClicked
         AdvancedSearchStudent f1=new AdvancedSearchStudent();
        panel.removeAll();
        f1.setSize(panel.getSize());
        Component add = panel.add(f1);
        panel.repaint();
        panel.revalidate();
        
        advancedSearch.setBorder(new LineBorder(Color.orange, 3));       
        searchStudentLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
         statusLbl.setBorder(new LineBorder(new Color(204, 0, 0), 1));
    }//GEN-LAST:event_advancedSearchMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel advancedSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel searchStudentLbl;
    private javax.swing.JLabel statusLbl;
    // End of variables declaration//GEN-END:variables
}
