/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nanapiyasa.view;

import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import static java.util.Objects.equals;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.ijse.sms.controller.UserAccountController;
import com.ijse.sms.model.UserAccounts;

/**
 *
 * @author Randula
 */
public class SignUp extends javax.swing.JDialog {

    /**
     * Creates new form SignUp
     */
 
    public SignUp(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        saveBtn.setEnabled(false);
         verifyTxt.setText(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        userNameTxt = new javax.swing.JTextField();
        passwordVerifyLbl1 = new javax.swing.JLabel();
        passwordVerifyTxt1 = new javax.swing.JPasswordField();
        nameLbl2 = new javax.swing.JLabel();
        userTypeLbl = new javax.swing.JLabel();
        userTypeCombo = new javax.swing.JComboBox();
        passwordLbl2 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        passwordTxt1 = new javax.swing.JPasswordField();
        cancelBtn1 = new javax.swing.JButton();
        verifyTxt = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        modifyBtn1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Setup Users");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("Create New User Account");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        userNameTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        userNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTxtActionPerformed(evt);
            }
        });
        getContentPane().add(userNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 310, 30));

        passwordVerifyLbl1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        passwordVerifyLbl1.setText("Confirm Password");
        getContentPane().add(passwordVerifyLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 120, -1));

        passwordVerifyTxt1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        passwordVerifyTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordVerifyTxt1ActionPerformed(evt);
            }
        });
        getContentPane().add(passwordVerifyTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 310, 30));

        nameLbl2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        nameLbl2.setText("User Name");
        getContentPane().add(nameLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 70, -1));

        userTypeLbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        userTypeLbl.setText("User Type");
        getContentPane().add(userTypeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 70, -1));

        userTypeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "User" }));
        userTypeCombo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        userTypeCombo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userTypeComboKeyPressed(evt);
            }
        });
        getContentPane().add(userTypeCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 310, 30));

        passwordLbl2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        passwordLbl2.setText("Password");
        getContentPane().add(passwordLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 70, -1));

        saveBtn.setBackground(new java.awt.Color(255, 255, 204));
        saveBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        saveBtn.setText("Save");
        saveBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 130, 40));

        passwordTxt1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        passwordTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTxt1ActionPerformed(evt);
            }
        });
        getContentPane().add(passwordTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 310, 30));

        cancelBtn1.setBackground(new java.awt.Color(255, 255, 204));
        cancelBtn1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cancelBtn1.setText("Cancel");
        cancelBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(cancelBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 130, 40));

        verifyTxt.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        verifyTxt.setForeground(new java.awt.Color(255, 0, 0));
        verifyTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        verifyTxt.setText("Verification Success");
        getContentPane().add(verifyTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 310, 70));

        jLabel11.setText("Modifications");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 520, -1, -1));

        modifyBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/modify.png"))); // NOI18N
        modifyBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modifyBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifyBtn1MouseClicked(evt);
            }
        });
        getContentPane().add(modifyBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/signup.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void passwordVerifyTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordVerifyTxt1ActionPerformed
        if(Arrays.equals(passwordTxt1.getPassword(),passwordVerifyTxt1.getPassword())){
            verifyTxt.setText("Password Verification Success");
            saveBtn.setEnabled(true);
        }else{
             verifyTxt.setText("Password Verification Faild");
             passwordTxt1.setText(null);
             passwordVerifyTxt1.setText(null);
             passwordTxt1.requestFocusInWindow();
        }
            
            
    }//GEN-LAST:event_passwordVerifyTxt1ActionPerformed

    private void userNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTxtActionPerformed
        userTypeCombo.requestFocusInWindow();
    }//GEN-LAST:event_userNameTxtActionPerformed

    private void userTypeComboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userTypeComboKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           passwordTxt1.requestFocusInWindow();
       }
    }//GEN-LAST:event_userTypeComboKeyPressed

    private void passwordTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTxt1ActionPerformed
        passwordVerifyTxt1.requestFocusInWindow();
    }//GEN-LAST:event_passwordTxt1ActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        String userName=userNameTxt.getText();
        String userType=(String)userTypeCombo.getSelectedItem();
        String password=passwordVerifyTxt1.getText();
        
        UserAccounts userAccounts=new UserAccounts(0, userName, password, userType);
        try {
            boolean isAdded=UserAccountController.addUser(userAccounts);
            if(isAdded){
                JOptionPane.showMessageDialog(this,"Successfully Saved");
            }else{
                 JOptionPane.showMessageDialog(this,"Saving Failed. Try Again");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_saveBtnActionPerformed

    private void cancelBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelBtn1ActionPerformed

    private void modifyBtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyBtn1MouseClicked
        new ModifyUsers(null, true).setVisible(true);
    }//GEN-LAST:event_modifyBtn1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SignUp dialog = new SignUp(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel modifyBtn1;
    private javax.swing.JLabel nameLbl2;
    private javax.swing.JLabel passwordLbl2;
    private javax.swing.JPasswordField passwordTxt1;
    private javax.swing.JLabel passwordVerifyLbl1;
    private javax.swing.JPasswordField passwordVerifyTxt1;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField userNameTxt;
    private javax.swing.JComboBox userTypeCombo;
    private javax.swing.JLabel userTypeLbl;
    private javax.swing.JLabel verifyTxt;
    // End of variables declaration//GEN-END:variables
}
