/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nanapiyasa.view;

import java.awt.Color;
import java.awt.Component;
import javax.swing.border.LineBorder;

/**
 *
 * @author Randula
 */
public class StudentAttendance extends javax.swing.JFrame {

    /**
     * Creates new form Attendance
     */
    public StudentAttendance() {
        initComponents();
         MarkAttendance f1=new MarkAttendance();
        panel.removeAll();
        f1.setSize(panel.getSize());
        Component add = panel.add(f1);
        panel.repaint();
        panel.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        refundPayment = new javax.swing.JLabel();
        markAttendanceLbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        advancedSearchAttendanceLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Attendance");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(900, 630));
        jPanel3.setLayout(null);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/background2.png"))); // NOI18N
        jPanel3.add(jLabel16);
        jLabel16.setBounds(0, 90, 835, 520);

        panel.add(jPanel3);
        jPanel3.setBounds(0, 0, 900, 630);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/background2.png"))); // NOI18N
        panel.add(jLabel2);
        jLabel2.setBounds(0, 82, 835, 528);

        jPanel1.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 900, 630));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Mark Attendance");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 120, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("View Attendance");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 120, 50));

        refundPayment.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        refundPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/labelSize.png"))); // NOI18N
        refundPayment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        refundPayment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refundPayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refundPaymentMouseClicked(evt);
            }
        });
        jPanel1.add(refundPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 210, 50));

        markAttendanceLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        markAttendanceLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/labelSize.png"))); // NOI18N
        markAttendanceLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        markAttendanceLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        markAttendanceLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                markAttendanceLblMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                markAttendanceLblMouseEntered(evt);
            }
        });
        jPanel1.add(markAttendanceLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 210, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Advanced Search Attendance");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 190, 50));

        advancedSearchAttendanceLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        advancedSearchAttendanceLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/labelSize.png"))); // NOI18N
        advancedSearchAttendanceLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        advancedSearchAttendanceLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        advancedSearchAttendanceLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                advancedSearchAttendanceLblMouseClicked(evt);
            }
        });
        jPanel1.add(advancedSearchAttendanceLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 210, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/background.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1160, 596));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void refundPaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refundPaymentMouseClicked
        ViewAttendance f1=new ViewAttendance();
        panel.removeAll();
        f1.setSize(panel.getSize());
        Component add = panel.add(f1);
        panel.repaint();
        panel.revalidate();
        refundPayment.setBorder(new LineBorder(Color.orange, 3));
        markAttendanceLbl.setBorder(new LineBorder(new Color(204, 0, 0),1));
        advancedSearchAttendanceLbl.setBorder(new LineBorder(new Color(204, 0, 0),1));
    }//GEN-LAST:event_refundPaymentMouseClicked

    private void markAttendanceLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_markAttendanceLblMouseClicked
        MarkAttendance f1=new MarkAttendance();
        panel.removeAll();
        f1.setSize(panel.getSize());
        Component add = panel.add(f1);
        panel.repaint();
        panel.revalidate();
        refundPayment.setBorder(new LineBorder(new Color(204, 0, 0),1));
       markAttendanceLbl.setBorder(new LineBorder(Color.orange, 3));
       advancedSearchAttendanceLbl.setBorder(new LineBorder(new Color(204, 0, 0),1));
    }//GEN-LAST:event_markAttendanceLblMouseClicked

    private void advancedSearchAttendanceLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_advancedSearchAttendanceLblMouseClicked
        AdvancedSearchAttendance f1=new AdvancedSearchAttendance();
        panel.removeAll();
        f1.setSize(panel.getSize());
        Component add = panel.add(f1);
        panel.repaint();
        panel.revalidate();
        advancedSearchAttendanceLbl.setBorder(new LineBorder(Color.orange, 3));
         markAttendanceLbl.setBorder(new LineBorder(new Color(204, 0, 0),1));
         refundPayment.setBorder(new LineBorder(new Color(204, 0, 0),1));
    }//GEN-LAST:event_advancedSearchAttendanceLblMouseClicked

    private void markAttendanceLblMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_markAttendanceLblMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_markAttendanceLblMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentAttendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentAttendance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel advancedSearchAttendanceLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel markAttendanceLbl;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel refundPayment;
    // End of variables declaration//GEN-END:variables
}
