/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nanapiyasa.view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.ijse.sms.controller.PaymentController;
import com.ijse.sms.util.Validation;
import com.ijse.sms.model.Payment;
/**
 *
 * @author Randula
 */
public class ViewPayment extends javax.swing.JPanel {

    /**
     * Creates new form ViewPayment
     */
    public ViewPayment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        reasonLbl = new javax.swing.JLabel();
        payIdLbl = new javax.swing.JLabel();
        discountLbl = new javax.swing.JLabel();
        paymentLbl = new javax.swing.JLabel();
        regIdLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dateTxt = new javax.swing.JTextField();
        discountTxt = new javax.swing.JTextField();
        paymentTxt = new javax.swing.JTextField();
        regIdTxt = new javax.swing.JTextField();
        payIdTxt = new javax.swing.JTextField();
        reloadBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        reasonTxt = new javax.swing.JTextField();
        durationLbl2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        clearBtn1 = new javax.swing.JButton();
        dateLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 630));
        jPanel1.setLayout(null);

        reasonLbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        reasonLbl.setText("Reason");
        jPanel1.add(reasonLbl);
        reasonLbl.setBounds(10, 340, 60, 30);

        payIdLbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        payIdLbl.setText("Payment ID");
        jPanel1.add(payIdLbl);
        payIdLbl.setBounds(10, 100, 70, 20);

        discountLbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        discountLbl.setText("Discount");
        jPanel1.add(discountLbl);
        discountLbl.setBounds(10, 240, 70, 30);

        paymentLbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        paymentLbl.setText("Payment");
        jPanel1.add(paymentLbl);
        paymentLbl.setBounds(10, 190, 60, 35);

        regIdLbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        regIdLbl.setText("Registration ID");
        jPanel1.add(regIdLbl);
        regIdLbl.setBounds(10, 140, 90, 30);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("View Payments");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 900, 40);

        dateTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        jPanel1.add(dateTxt);
        dateTxt.setBounds(100, 290, 320, 35);

        discountTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        jPanel1.add(discountTxt);
        discountTxt.setBounds(100, 240, 320, 35);

        paymentTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        paymentTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                paymentTxtKeyTyped(evt);
            }
        });
        jPanel1.add(paymentTxt);
        paymentTxt.setBounds(100, 190, 320, 35);

        regIdTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        jPanel1.add(regIdTxt);
        regIdTxt.setBounds(100, 140, 320, 35);

        payIdTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        payIdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payIdTxtActionPerformed(evt);
            }
        });
        jPanel1.add(payIdTxt);
        payIdTxt.setBounds(101, 90, 190, 35);

        reloadBtn.setBackground(new java.awt.Color(255, 233, 248));
        reloadBtn.setText("Reload");
        reloadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadBtnActionPerformed(evt);
            }
        });
        jPanel1.add(reloadBtn);
        reloadBtn.setBounds(430, 390, 110, 30);

        editBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/Edit.png"))); // NOI18N
        editBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editBtnMouseClicked(evt);
            }
        });
        jPanel1.add(editBtn);
        editBtn.setBounds(120, 470, 80, 70);

        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/Delete.png"))); // NOI18N
        deleteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteBtnMouseClicked(evt);
            }
        });
        jPanel1.add(deleteBtn);
        deleteBtn.setBounds(280, 470, 70, 70);

        jLabel5.setText("Save Changes");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(120, 540, 70, 20);

        jLabel3.setText("Remove");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(290, 540, 50, 20);

        reasonTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)));
        jPanel1.add(reasonTxt);
        reasonTxt.setBounds(100, 340, 320, 35);

        durationLbl2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        durationLbl2.setText("Reason");
        jPanel1.add(durationLbl2);
        durationLbl2.setBounds(-420, 410, 60, 30);

        table.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Reg ID", "Payment", "Discount", "Paid Date", "Reason"
            }
        ));
        table.setFillsViewportHeight(true);
        table.setGridColor(new java.awt.Color(204, 0, 0));
        table.setRowHeight(20);
        table.setSelectionBackground(new java.awt.Color(255, 204, 153));
        table.setSelectionForeground(new java.awt.Color(0, 0, 0));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setMinWidth(50);
            table.getColumnModel().getColumn(0).setPreferredWidth(50);
            table.getColumnModel().getColumn(0).setMaxWidth(50);
            table.getColumnModel().getColumn(1).setMinWidth(100);
            table.getColumnModel().getColumn(1).setPreferredWidth(100);
            table.getColumnModel().getColumn(1).setMaxWidth(100);
            table.getColumnModel().getColumn(2).setMinWidth(75);
            table.getColumnModel().getColumn(2).setPreferredWidth(75);
            table.getColumnModel().getColumn(2).setMaxWidth(75);
            table.getColumnModel().getColumn(3).setMinWidth(75);
            table.getColumnModel().getColumn(3).setPreferredWidth(75);
            table.getColumnModel().getColumn(3).setMaxWidth(75);
            table.getColumnModel().getColumn(5).setMinWidth(50);
            table.getColumnModel().getColumn(5).setPreferredWidth(50);
            table.getColumnModel().getColumn(5).setMaxWidth(50);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(430, 80, 460, 300);

        clearBtn1.setBackground(new java.awt.Color(255, 233, 248));
        clearBtn1.setText("Clear");
        clearBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(clearBtn1);
        clearBtn1.setBounds(100, 390, 110, 30);

        dateLbl.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        dateLbl.setText("Date");
        jPanel1.add(dateLbl);
        dateLbl.setBounds(10, 290, 60, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nanapiyasa/view/Images/background2.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 90, 835, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void reloadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadBtnActionPerformed
        try {
            ArrayList<Payment>paymentList=PaymentController.viewAllPayment();
             DefaultTableModel dtm = (DefaultTableModel) table.getModel();
             dtm.setRowCount(0);
            for(Payment payment: paymentList){
                Object[] rows={payment.getPayID(),payment.getRegID(),payment.getPayment(),payment.getDiscount(),payment.getPayDate(),payment.getPaymentCategory()};
		dtm.addRow(rows);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ViewPayment.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ViewPayment.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_reloadBtnActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        int i=table.getSelectedRow();
	payIdTxt.setText((String)table.getValueAt(i,0));
	regIdTxt.setText((String)table.getValueAt(i,1));
        paymentTxt.setText((String)table.getValueAt(i,2).toString());
        discountTxt.setText((String)table.getValueAt(i,3).toString());
        dateTxt.setText((String)table.getValueAt(i,4));
        reasonTxt.setText((String)table.getValueAt(i,5));
        
    }//GEN-LAST:event_tableMouseClicked

    private void payIdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payIdTxtActionPerformed
        String payId=payIdTxt.getText();
        
        try {
            Payment payment=PaymentController.searchPayment(payId);
            if(payment!=null){
                regIdTxt.setText(payment.getRegID());
                paymentTxt.setText(Double.toString(payment.getPayment()));
                discountTxt.setText(Double.toString(payment.getDiscount()));
                dateTxt.setText(payment.getPayDate());
                reasonTxt.setText(payment.getPaymentCategory());
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ViewPayment.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ViewPayment.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_payIdTxtActionPerformed

    private void editBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBtnMouseClicked
     
            int res=JOptionPane.showOptionDialog(this, "Dou you want to save changes?","Options", 0,0,null,null,null );
            if(res==0){
               String payId=payIdTxt.getText();
               String regId=regIdTxt.getText();
               Double amount=Double.parseDouble(paymentTxt.getText());
               Double discount=Double.parseDouble(discountTxt.getText());
               String date=dateTxt.getText();
               String reason=reasonTxt.getText();
               

                Payment payment=new Payment(payId, regId, amount, discount, date, reason);

                try {
                    boolean isUpdated=PaymentController.updatePayment(payment);
                    if(isUpdated){
                        JOptionPane.showMessageDialog(this, "Saved Changes");  
                    }else{
                         JOptionPane.showMessageDialog(this, "Can not update Payment Details");  
                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(ManageCertificate.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(ManageCertificate.class.getName()).log(Level.SEVERE, null, ex);
                }
           }

    }//GEN-LAST:event_editBtnMouseClicked

    private void deleteBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteBtnMouseClicked
          int res=JOptionPane.showOptionDialog(this, "Dou you want to Delete this User?","Options", 0,0,null,null,null );
            if(res==0){
             try {
                 String id=payIdTxt.getText();
                 boolean isDeleted=PaymentController.deletePayment(id);
                 if(isDeleted){
                       JOptionPane.showMessageDialog(this,"Payment Removed");
                 }else{
                       JOptionPane.showMessageDialog(this,"Try Again");
                 }
             } catch (ClassNotFoundException ex) {
                 Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
             } catch (SQLException ex) {
                 Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
             }
                
            }
    }//GEN-LAST:event_deleteBtnMouseClicked

    private void clearBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtn1ActionPerformed
        payIdTxt.setText(null);
        regIdTxt.setText(null);
        paymentTxt.setText(null);
        discountTxt.setText(null);
        dateTxt.setText(null);
        reasonTxt.setText(null);
    }//GEN-LAST:event_clearBtn1ActionPerformed

    private void paymentTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paymentTxtKeyTyped
        Validation.priceText(paymentTxt);
    }//GEN-LAST:event_paymentTxtKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearBtn1;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JTextField dateTxt;
    private javax.swing.JLabel deleteBtn;
    private javax.swing.JLabel discountLbl;
    private javax.swing.JTextField discountTxt;
    private javax.swing.JLabel durationLbl2;
    private javax.swing.JLabel editBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel payIdLbl;
    private javax.swing.JTextField payIdTxt;
    private javax.swing.JLabel paymentLbl;
    private javax.swing.JTextField paymentTxt;
    private javax.swing.JLabel reasonLbl;
    private javax.swing.JTextField reasonTxt;
    private javax.swing.JLabel regIdLbl;
    private javax.swing.JTextField regIdTxt;
    private javax.swing.JButton reloadBtn;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
